### ISSUE TITLE
glob-watcher is no longer used by gulp

### ISSUE THREAD

**Issue by SgtPooki** [gulpjs/glob-watcher#24] opened 2015-12-06 20:18 UTC
So, this package should be deprecated or removed since it's contributing to a dependency chain that contains other deprecated packages.

I opened another issue (#23) for this, but it was closed and muted without any attempt to actually resolve or inform the public about the issue to help reduce these contacts from continuing to come in. I reached out to @contra privately and after informing me that 
>We don't use the glob-watcher module at all in gulp anymore.

he said I should 

>... talk on github, private communications aren't helpful when people search for the same thing down the road.

I completely agree, and my response to his email was as follows: 

>I agree that private communications aren't helpful and am a huge advocate for communication and transparency; But I can't continue to talk on github because phated closed the issue and locked down comments. As far as I know, there is no way to get around that. I guess I could create a glob-watcher room on gitter.im, but I don't know that you use it and it's very unlikely that anyone else would come to talk about gulpjs's glob-watcher module on a channel that I own. And I shouldn't own it.

>Just so you know, I installed gulp on a new machine yesterday and got the lodash deprecation warning and started investigating. It is extremely messy, but deprecation *is* a good thing. Apparently vinyl-fs has a glob-watcher dependency, so I guess it isn't truly gulp at fault here. However, the gulpjs org on github owns the glob-watcher dependency which still depends on gaze.... etc. 

>As the owner of the glob-watcher package, which other developers are using, it is their(your?) responsibility to either maintain your package or allow other people to resolve the issues you refuse to. As an open-source and largely influential package in the node/javascript community gulpjs should, at the very least, post a warning to not use glob-watcher anymore and suggest the alternatives, or it should be more open and willing to feedback and resolving issues this package presents.

>I understand your want to keep issues as low as possible, but that effort is absolutely meaningless if you're not actually working towards resolving issues.

>I will open a new issue on glob-watcher saying the same so that the public can see it.

**Comment by SgtPooki** [comment] 2015-12-06 20:31
See https://github.com/lodash/lodash/issues/1686 for additional information

**Comment by phated** [comment] 2015-12-06 22:39
Duplicate of #22 - please search for issues before opening another one.

**Closed by phated** 2015-12-06 22:39 UTC

**Comment by contra** [comment] 2015-12-06 22:42
@SgtPooki I think you're making this a bigger deal than it needs to be.

Facts:
- gulp 3.x (the latest available release) uses glob-watcher, so we are not deprecating it
- gulp 4.x (the upcoming release) does NOT use glob-watcher, so we are going to deprecate this module when this is on npm

The issue you are referencing has nothing to do with gulp or glob-watcher or any of this: the lodash deprecation warnings are because the author of lodash made a poor decision. The issue was closed because @phated believes that other people's dumb choices are not ours to fix.

It looks like the deprecation warnings have been removed (from the issue you linked) and your problem has been solved so I'm not sure what you're looking for here.

**Comment by contra** [comment] 2015-12-06 22:43
@phated Please stop locking issues - every time you lock an issue people start emailing me instead.

**Comment by phated** [comment] 2015-12-06 23:11
@contra correction, the deprecation warning was not removed but it actually means nothing to end users. The issue was opened because there was a person complaining it caused windows to exit with error code > 0.  However, after a discussion with npm and microsoft, it was determined that user was incorrect and the error code was still 0 when npm writes to stderr on windows.  A deprecation warning was still an uninformed and mistaken move by lodash but it doesn't seem like it will be removed.  The warning doesn't mean anything though because there aren't bugs in the code our deps of deps of deps of deps are using.

The issues get locked because there is nothing else we can do and I am sick of being attacked in threads by someone blowing shit out of proportion.  Sorry that users don't understand what that means and email you.

**Comment by contra** [comment] 2015-12-06 23:20
@phated Understand, better to unwatch issues than lock though or people get frustrated and write angry tweets/emails about how we don't care about what they have to say and are total dickheads.
